export const projects = [
  {
    title: "LeetCode Clone Backend",
    subtitle: "Scalable Microservices Backend for a Coding Platform",
    description:
      "A robust backend for a LeetCode-inspired coding platform, built with a microservices architecture to handle high concurrency, real-time updates, and task queues. Designed for scalability, reliability, and seamless user experience.",
    github: "https://github.com/gouravmarch20/leetcode-problem-service",
    live: "http://13.50.198.80/choose-account",
    gradient: "from-indigo-600 to-blue-700",
    status: "Completed",
    category: "Backend / Web Application",
    highlight: "Featured",
    timeline: "4 months",
    clientType: "Personal / Portfolio Project",
  },

  {
    title: "Stationery Hut",
    subtitle: "E-commerce Platform for Stationary Products",
    description:
      "A fully functional e-commerce application for stationary products built with React and Context API. Features include product browsing, cart management, and seamless checkout experience.",
    github: "https://github.com/gouravmarch20/stationery-hut",
    live: "https://stationery-hut.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "E-commerce / Web Application",
    highlight: "",
    timeline: "2 months",
    clientType: "Personal / Portfolio Project",
  },
  {
    title: "V Play",
    subtitle: "Video Library Application",
    description:
      "A video library app built with React and Context API. Features include video browsing, playlists, watch later, and history tracking for a complete video streaming experience.",
    github: "https://github.com/gouravmarch20/v-play",
    live: "https://v-play.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "Media / Web Application",
    highlight: "",
    timeline: "1.5 months",
    clientType: "Personal / Portfolio Project",
  },
  {
    title: "Pa Media",
    subtitle: "Social Media Platform",
    description:
      "A modern social media web application built with React, Redux Toolkit, and Material UI. Features rich user interactions, responsive design, and state-of-the-art UI components.",
    github: "https://github.com/gouravmarch20/pa-media",
    live: "https://pa-media.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "Social Media / Web Application",
    highlight: "",
    timeline: "2 months",
    clientType: "Personal / Portfolio Project",
  },
  {
    title: "Tri Quiz",
    subtitle: "Interactive Quiz Application",
    description:
      "A quiz application built with React and TypeScript. Features multiple categories, timed questions, score tracking, and instant feedback for an engaging learning experience.",
    github: "https://github.com/gouravmarch20/tri-quiz",
    live: "https://tri-quiz.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "Education / Web Application",
    highlight: "",
    timeline: "3 weeks",
    clientType: "Personal / Portfolio Project",
  },
  {
    title: "Cheet CSS",
    subtitle: "Lightweight UI Component Library",
    description:
      "A custom-built, lightweight UI component library designed to help developers create trendy and modern-looking websites quickly. Includes pre-styled components and utilities.",
    github: "https://github.com/gouravmarch20/css-cheat",
    live: "https://cheet-css.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "Library / Developer Tools",
    highlight: "",
    timeline: "1 month",
    clientType: "Personal / Portfolio Project",
  },

  {
    title: "Link Tree",
    subtitle: "Personal Link Hub",
    description:
      "A personal link aggregator created using HTML and CSS that displays all important links in one place. Clean, simple design for easy navigation to social profiles and projects.",
    github: "https://github.com/gouravmarch20/linktr.ee-gouravmarch20",
    live: "https://linktree-gouravmarch20.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "Personal / Portfolio",
    highlight: "",
    timeline: "1 week",
    clientType: "Personal / Portfolio Project",
  },

  {
    title: "Risby Restaurant",
    subtitle: "JAMstack Restaurant Website",
    description:
      "A blazing-fast restaurant website created using Gatsby and Contentful CMS. Built with JAMstack architecture for optimal performance, loading in less than 2 seconds.",
    github: "https://github.com/gouravmarch20/gatsby-recepie-web",
    live: "https://risby-restaurant.netlify.app/",
    gradient: "from-indigo-600 to-blue-700",
    status: "Live",
    category: "JAMstack / Web Application",
    highlight: "",
    timeline: "1.5 months",
    clientType: "Personal / Portfolio Project",
  },
];
